### ISSUE TITLE
node-chakracore fails on Travis CI's trusty environment

### ISSUE THREAD

**Issue by kfarnung** [nodejs/node-chakracore#528]
* **Version**: v8.11.1/v10.0.0
* **Platform**: Ubuntu Linux 14.04.5
* **Subsystem**:

While trying to use Travis CI following the [NVS documentation](https://github.com/jasongin/nvs/blob/master/doc/CI.md) I ran into an issue where node-chakracore appears to be missing the requisite version of GLIBCXX:

```console
$ node --version
node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)
```

[log.txt](https://github.com/nodejs/node-chakracore/files/1962075/log.txt)

Since releases are built on 14.04, it would be ideal if they didn't require any extra dependencies to run.

The workaround is to add some packages to the [CI config](https://raw.githubusercontent.com/kfarnung/puzzle-lib/master/.travis.yml), but it seems like we should use the included version, if possible:
```yaml
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-4.9-dev
```
